/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vut;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Pana
 */
public class EmployeeDetailsEntry extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeDetailsEntry
     */
    public EmployeeDetailsEntry() {
        initComponents();
    }
   
    public void clearCont(){
        txtEmpName.setText("");
        txtEmpNo.setText("");
        txtDept.setText("");
        txtTitle.setText("");
        rbtnMale.setSelected(false);
        rbtnFem.setSelected(false);
        txtEmpNo.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEmpDetails = new javax.swing.JPanel();
        lblNo = new javax.swing.JLabel();
        lblEmpName = new javax.swing.JLabel();
        lblDept = new javax.swing.JLabel();
        txtEmpNo = new javax.swing.JTextField();
        txtEmpName = new javax.swing.JTextField();
        txtDept = new javax.swing.JTextField();
        lbljTitle = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        pnlGender = new javax.swing.JPanel();
        rbtnFem = new javax.swing.JRadioButton();
        rbtnMale = new javax.swing.JRadioButton();
        pnlButton = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("frmEmpDetails");

        pnlEmpDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Details Entry", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));

        lblNo.setText("Emplyee Number :");
        lblNo.setRequestFocusEnabled(false);

        lblEmpName.setText("Employee Name :");

        lblDept.setText("Job Department : ");
        lblDept.setToolTipText("");

        lbljTitle.setText("Job Title");

        pnlGender.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Gender"));

        rbtnFem.setText("Female");

        rbtnMale.setText("Male");
        rbtnMale.setActionCommand("Male");

        javax.swing.GroupLayout pnlGenderLayout = new javax.swing.GroupLayout(pnlGender);
        pnlGender.setLayout(pnlGenderLayout);
        pnlGenderLayout.setHorizontalGroup(
            pnlGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGenderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnFem)
                    .addComponent(rbtnMale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlGenderLayout.setVerticalGroup(
            pnlGenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGenderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnFem)
                .addGap(18, 18, 18)
                .addComponent(rbtnMale)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        rbtnFem.getAccessibleContext().setAccessibleName("rbFemale");
        rbtnMale.getAccessibleContext().setAccessibleName("rbMale");

        pnlButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSave.setLabel("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnView.setLabel("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonLayout = new javax.swing.GroupLayout(pnlButton);
        pnlButton.setLayout(pnlButtonLayout);
        pnlButtonLayout.setHorizontalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnlButtonLayout.setVerticalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnView)
                .addGap(28, 28, 28))
        );

        btnSave.getAccessibleContext().setAccessibleName("SaveButton");
        btnView.getAccessibleContext().setAccessibleName("ViewButton");

        javax.swing.GroupLayout pnlEmpDetailsLayout = new javax.swing.GroupLayout(pnlEmpDetails);
        pnlEmpDetails.setLayout(pnlEmpDetailsLayout);
        pnlEmpDetailsLayout.setHorizontalGroup(
            pnlEmpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmpDetailsLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlEmpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEmpDetailsLayout.createSequentialGroup()
                        .addGroup(pnlEmpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEmpDetailsLayout.createSequentialGroup()
                                .addGroup(pnlEmpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblEmpName)
                                    .addComponent(lblDept))
                                .addGap(109, 109, 109))
                            .addGroup(pnlEmpDetailsLayout.createSequentialGroup()
                                .addComponent(lbljTitle)
                                .addGap(162, 162, 162)))
                        .addGroup(pnlEmpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDept, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(txtEmpName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmpNo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitle))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlEmpDetailsLayout.createSequentialGroup()
                        .addComponent(pnlGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
        );
        pnlEmpDetailsLayout.setVerticalGroup(
            pnlEmpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmpDetailsLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(pnlEmpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNo)
                    .addComponent(txtEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlEmpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpName)
                    .addComponent(txtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlEmpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDept)
                    .addComponent(txtDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEmpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbljTitle)
                    .addComponent(txtTitle))
                .addGap(44, 44, 44)
                .addGroup(pnlEmpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        lblNo.getAccessibleContext().setAccessibleName("EmployeeNo");
        lblEmpName.getAccessibleContext().setAccessibleName("EmpName");
        lblDept.getAccessibleContext().setAccessibleName("jobDept");
        txtEmpNo.getAccessibleContext().setAccessibleName("EmpNo");
        txtEmpName.getAccessibleContext().setAccessibleName("empName");
        txtDept.getAccessibleContext().setAccessibleName("JobDept");
        lbljTitle.getAccessibleContext().setAccessibleName("jobTitle");
        txtTitle.getAccessibleContext().setAccessibleName("JobTitle");
        pnlGender.getAccessibleContext().setAccessibleName("GenderPanel");
        pnlButton.getAccessibleContext().setAccessibleName("ButtonPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEmpDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(pnlEmpDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        //check if the user has entered any data in the text fields
        if ((!txtEmpNo.getText().isEmpty())&&(!txtEmpName.getText().isEmpty())
                && (!txtDept.getText().isEmpty()) && (!txtTitle.getText().isEmpty())) {
            Employee objEmploEntity = null;
            Job objJob = null;
            /**
             *Declaring an object variable of type employee class 
             *we declare these objects at class level because they going to be used
             * by more than one parameter / method
             */
            //create a group , to store the radio buttons so that only one of them is selected.
            ButtonGroup grpRadioBtn = new ButtonGroup();
                grpRadioBtn.add(rbtnFem);
                grpRadioBtn.add(rbtnMale);
            try {
                //try catch for handling exceptions / validations
                objJob = new Job(txtTitle.getText(),txtDept.getText());
                //create a objct of job first since its an instance of employee
                //and the constructor of the employee class receives this object, along with other parameters
                
                if (rbtnFem.isSelected()) {
                    //creating an object of type employee, which receives the job as a parameter in the constructor
                    //checking to see which radio button is selected, to trigger object instantiation
                    objEmploEntity = new Employee(txtEmpNo.getText(), txtEmpName.getText(),Employee.Gender.FEMALE, objJob);
                }
                else{
                
                    objEmploEntity = new Employee(txtEmpNo.getText(), txtEmpName.getText(),Employee.Gender.MALE, objJob);
                }
                /**
                 *Saving the created Employee object in an array list
                 *THE VIEW EMPLOYEE FORM , IS WHERE THE ARRAY LIST IS CREATED , AS A PUBLIC AND STATIC INSTANCE VARIABLE
                 * this means i can access the array using the name of the class that declares it.
                 */
                ViewEmployeeDetails.employeeEntityList.add(objEmploEntity);
                
            } catch (IllegalArgumentException ex)
            {
                JOptionPane.showMessageDialog(null,"Error Processing The Command!! "+ ex);
            }
            //CALLS THE CLEAR CONTROLS METHOD DEFINED IN THIS CLASS
           clearCont();
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        //checking to see if there is any object stored in the array
        if (ViewEmployeeDetails.employeeEntityList.size() > 0) {
            ViewEmployeeDetails objViewEmp = new ViewEmployeeDetails();
            //creating an instance of the form to be loaded
            objViewEmp.setVisible(true);
            //Display the form
            objViewEmp.setTitle("Employee Details Frame");
        }
        else{
        
            JOptionPane.showMessageDialog(null, "Please Capture @Least 1 employee in the Database.");
        }
    }//GEN-LAST:event_btnViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetailsEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetailsEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetailsEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetailsEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDetailsEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel lblDept;
    private javax.swing.JLabel lblEmpName;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lbljTitle;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlEmpDetails;
    private javax.swing.JPanel pnlGender;
    private javax.swing.JRadioButton rbtnFem;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JTextField txtDept;
    private javax.swing.JTextField txtEmpName;
    private javax.swing.JTextField txtEmpNo;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
