/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vut.emp;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import vut.Employee;
import vut.Job;
/**
 *
 * @author Pana
 */
public class JobDetails extends javax.swing.JFrame {

    /**
     * Creates new form JobDetails
     */
    public JobDetails() {
        initComponents();
    }
    public void clearControls(){
        txtEmpName.setText("");
        txtEmpNo.setText("");
        rdoFemale.setEnabled(false);
        rdoMale.setEnabled(false);
        btnAdd.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlComp = new javax.swing.JPanel();
        pnlRadio = new javax.swing.JPanel();
        rdoMale = new javax.swing.JRadioButton();
        rdoFemale = new javax.swing.JRadioButton();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblEmpNo = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtEmpName = new javax.swing.JTextField();
        txtEmpNo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Entry Frame");
        setBackground(new java.awt.Color(153, 255, 255));

        pnlComp.setBackground(new java.awt.Color(204, 255, 153));
        pnlComp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Employee Details ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        pnlRadio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Gender", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        rdoMale.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        rdoMale.setText("Male");

        rdoFemale.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rdoFemale.setText("Female");

        javax.swing.GroupLayout pnlRadioLayout = new javax.swing.GroupLayout(pnlRadio);
        pnlRadio.setLayout(pnlRadioLayout);
        pnlRadioLayout.setHorizontalGroup(
            pnlRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRadioLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoFemale)
                    .addComponent(rdoMale))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pnlRadioLayout.setVerticalGroup(
            pnlRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRadioLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(rdoMale)
                .addGap(18, 18, 18)
                .addComponent(rdoFemale)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnAdd.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        btnAdd.setText("Add Employee");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblEmpNo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblEmpNo.setText("Emplyee Number:");

        lblName.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblName.setText("Employee Name:");

        javax.swing.GroupLayout pnlCompLayout = new javax.swing.GroupLayout(pnlComp);
        pnlComp.setLayout(pnlCompLayout);
        pnlCompLayout.setHorizontalGroup(
            pnlCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCompLayout.createSequentialGroup()
                .addGroup(pnlCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCompLayout.createSequentialGroup()
                        .addGap(0, 63, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCompLayout.createSequentialGroup()
                        .addComponent(lblName)
                        .addGap(22, 22, 22)
                        .addComponent(txtEmpName))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCompLayout.createSequentialGroup()
                        .addComponent(lblEmpNo)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmpNo)))
                .addGap(35, 35, 35)
                .addGroup(pnlCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        pnlCompLayout.setVerticalGroup(
            pnlCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCompLayout.createSequentialGroup()
                .addGroup(pnlCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCompLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCompLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(pnlCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmpNo)
                            .addComponent(txtEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(txtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(pnlCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnAdd))
                .addGap(121, 121, 121))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(pnlComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pnlComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        //check if the combo boxes contain any input 
       
        if ((!txtEmpNo.getText().isEmpty())&& txtEmpName.getText().isEmpty()) {
            Employee objEmp = null;
            Job jobObject = null;
            //declare them as in example one, not refereced
            /**
             * There is no input for the job object on this form
             * but because the employee constructor requires it as a parameter you must declare it
             * The employee class requires 4 parameters
             */
            try {
                if (rdoFemale.isSelected()) {
                    objEmp = new Employee(txtEmpNo.getText(), txtEmpName.getText(), Employee.Gender.FEMALE, jobObject);
                }
                else{
                    objEmp = new Employee(txtEmpNo.getText(), txtEmpName.getText(), Employee.Gender.MALE, jobObject);
                }
                /**
                 *we add the created object in an array list created in the EmpDetails form
                 */
             EmployeeDetails.employeeEntityList.add(objEmp);
             
            } catch (IllegalArgumentException e)
            {
                JOptionPane.showMessageDialog(null, "Error! "+e.getMessage());
            }
            btnAdd.setEnabled(true);
            clearControls();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        EmployeeDetails objEmpFrame = new EmployeeDetails();
        objEmpFrame.setVisible(true);
        objEmpFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        objEmpFrame.setTitle("Adding A New Employee To The Database");
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JobDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JobDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JobDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JobDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JobDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblEmpNo;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel pnlComp;
    private javax.swing.JPanel pnlRadio;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JTextField txtEmpName;
    private javax.swing.JTextField txtEmpNo;
    // End of variables declaration//GEN-END:variables
}
