/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package std;

/**
 *
 * @author Pana
 */
public class StudentHome extends javax.swing.JFrame {

    /**
     * Creates new form StudentHome
     */
    public StudentHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmFile = new javax.swing.JMenu();
        miExit = new javax.swing.JMenuItem();
        jmAdd = new javax.swing.JMenu();
        miAddStud = new javax.swing.JMenuItem();
        miAddCourse = new javax.swing.JMenuItem();
        jmEdit = new javax.swing.JMenu();
        miEditStud = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome To The 9ino6ano Academy");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pana\\Documents\\IT\\Development Software\\GUI\\Pics\\Pics\\men.png")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pana\\Documents\\IT\\Development Software\\GUI\\map1.jpg")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pana\\Documents\\IT\\Development Software\\GUI\\enemy4.jpg")); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pana\\Documents\\IT\\Development Software\\GUI\\msn.jpg")); // NOI18N

        jmFile.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pana\\Documents\\IT\\Development Software\\GUI\\Pics\\Pics\\folder.png")); // NOI18N
        jmFile.setText("File");
        jmFile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        miExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        miExit.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pana\\Documents\\IT\\Development Software\\GUI\\Pics\\Pics\\exit.png")); // NOI18N
        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        jmFile.add(miExit);

        jMenuBar1.add(jmFile);

        jmAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pana\\Documents\\IT\\Development Software\\GUI\\Pics\\Pics\\add.png")); // NOI18N
        jmAdd.setText("Add");
        jmAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        miAddStud.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        miAddStud.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pana\\Documents\\IT\\Development Software\\GUI\\Pics\\Pics\\addemployee.png")); // NOI18N
        miAddStud.setText("Add Student");
        miAddStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddStudActionPerformed(evt);
            }
        });
        jmAdd.add(miAddStud);

        miAddCourse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        miAddCourse.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pana\\Documents\\IT\\Development Software\\GUI\\Pics\\Pics\\job.png")); // NOI18N
        miAddCourse.setText("Add Course");
        miAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddCourseActionPerformed(evt);
            }
        });
        jmAdd.add(miAddCourse);

        jMenuBar1.add(jmAdd);

        jmEdit.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pana\\Documents\\IT\\Development Software\\GUI\\Pics\\Pics\\edit.png")); // NOI18N
        jmEdit.setText("Edit");
        jmEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        miEditStud.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        miEditStud.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pana\\Documents\\IT\\Development Software\\GUI\\enemy1.jpg")); // NOI18N
        miEditStud.setText("Edit Student Record");
        miEditStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEditStudActionPerformed(evt);
            }
        });
        jmEdit.add(miEditStud);

        jMenuBar1.add(jmEdit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        System.out.println("Goodbye......#96");
    }//GEN-LAST:event_miExitActionPerformed

    private void miAddStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddStudActionPerformed
        // TODO add your handling code here:
        new AddStudent().setVisible(true);
    }//GEN-LAST:event_miAddStudActionPerformed

    private void miAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddCourseActionPerformed
        // TODO add your handling code here:
        new AddCourse().setVisible(true);
    }//GEN-LAST:event_miAddCourseActionPerformed

    private void miEditStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEditStudActionPerformed
        // TODO add your handling code here:
        new EditStudent().setVisible(true);
    }//GEN-LAST:event_miEditStudActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmAdd;
    private javax.swing.JMenu jmEdit;
    private javax.swing.JMenu jmFile;
    private javax.swing.JMenuItem miAddCourse;
    private javax.swing.JMenuItem miAddStud;
    private javax.swing.JMenuItem miEditStud;
    private javax.swing.JMenuItem miExit;
    // End of variables declaration//GEN-END:variables
}
