/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vut.emp;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import vut.Employee;
import vut.Job;
/**
 *
 * @author Pana
 */
public class EmployeeDetails extends javax.swing.JFrame {

    public static ArrayList<Employee> employeeEntityList;
    /**
     * Creates new form EmployeeDetails
     */
    public void loadComboBox(){
        //clearing the combo box
        cboEmpNo.removeAllItems();
        
        //using an enhanced for loop to store all objects
        for (Employee objEmp : employeeEntityList) {
            cboEmpNo.addItem(objEmp.getEmpNumber().toString());
        }
    }
    public EmployeeDetails() {
        initComponents();
        loadComboBox();
    }
    //create a local variable , that will serve as a selected employee from the combo box
    //provide getter and setter methods for this employee
    //The class needs to keep trackk of an SELECTED EMPLOYEE OBJECT,
    //Which will be selected in the COMBOBOX procedure

    private Employee selectedEmployee;
    //provide an accessor/getter method
    public Employee getSelectedEmployee(){
    
        return selectedEmployee;
    }
    //provide an mutator/setter method
    public void setSelectedEmployee(Employee selEmp){
        this.selectedEmployee = selEmp;
    }
    //create an clear controls method
    public void clearControls(){
        txtEmpName.setText("");
        txtEmpNo.setText("");
        txtJDept.setText("");
        txtJTitle.setText("");
        cboEmpNo.setEnabled(false);
        btnNew.requestFocus();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnEmploEntry = new javax.swing.JPanel();
        lblCboEmpNo = new javax.swing.JLabel();
        lblEmpName = new javax.swing.JLabel();
        lblEmpNo = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtEmpName = new javax.swing.JTextField();
        txtEmpNo = new javax.swing.JTextField();
        txtJTitle = new javax.swing.JTextField();
        cboEmpNo = new javax.swing.JComboBox();
        btnSave = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        lblDept = new javax.swing.JLabel();
        txtJDept = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Job Details Frame");
        setBackground(new java.awt.Color(51, 255, 204));
        setLocationByPlatform(true);
        setName(""); // NOI18N

        pnEmploEntry.setBackground(new java.awt.Color(204, 255, 204));
        pnEmploEntry.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Job Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        lblCboEmpNo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblCboEmpNo.setText("Select An Employee No:");

        lblEmpName.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblEmpName.setText("Employee Name:");

        lblEmpNo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblEmpNo.setText("Employee No:");

        lblTitle.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblTitle.setText("Job Title:");

        cboEmpNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEmpNoActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnNew.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnNew.setText("New Employee");

        lblDept.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblDept.setText("Job Department:");

        javax.swing.GroupLayout pnEmploEntryLayout = new javax.swing.GroupLayout(pnEmploEntry);
        pnEmploEntry.setLayout(pnEmploEntryLayout);
        pnEmploEntryLayout.setHorizontalGroup(
            pnEmploEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEmploEntryLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnEmploEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCboEmpNo)
                    .addComponent(lblEmpName)
                    .addComponent(lblTitle)
                    .addComponent(lblEmpNo)
                    .addComponent(lblDept)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnEmploEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnEmploEntryLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(pnEmploEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboEmpNo, 0, 124, Short.MAX_VALUE)
                            .addComponent(txtEmpName)
                            .addComponent(txtEmpNo)
                            .addComponent(txtJTitle)
                            .addComponent(txtJDept)))
                    .addGroup(pnEmploEntryLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnEmploEntryLayout.setVerticalGroup(
            pnEmploEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEmploEntryLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnEmploEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCboEmpNo)
                    .addComponent(cboEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEmploEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmpName)
                    .addComponent(txtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEmploEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmpNo)
                    .addComponent(txtEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnEmploEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(txtJTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnEmploEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDept)
                    .addComponent(txtJDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnEmploEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnNew))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnEmploEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(pnEmploEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboEmpNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEmpNoActionPerformed
        // TODO add your handling code here:
        if (cboEmpNo.getSelectedItem() == null) {
            return;
        }
        clearControls();
        /*
        *Looping through the arraylist to find the object 
        whose employee number is selected in the combo box.
        */
        for (Employee empEntityList1 : employeeEntityList) {
            String empNumber = cboEmpNo.getSelectedItem().toString();
            /**
             *SHOULD THE MATCH BE FOUND IN THE ARRAY,. THEREAFTER WE
             *Displaying the Employee name and Employee number in the text boxes.
             */
            if (empNumber.equals(empEntityList1.getEmpNumber())) {
                txtEmpName.setText(empEntityList1.getEmpNumber());
                txtEmpNo.setText(empEntityList1.getEmpNumber());
               
                //STORING THE SELECTED OBJECT [employee]
                //using the locally declare get/set methods of SelectedEmployee
                setSelectedEmployee(empEntityList1);
            }
        }/*
        *Checking if the selected employee object, has some details 
        if so, check if the selected employee has job details
        if not, enter them in the fields provided
        
        */
        if (getSelectedEmployee().getEmpJob() == null) {
            return;
        }
        txtJDept.setText(getSelectedEmployee().getEmpJob().getJobDepartment());
        txtJDept.setText(getSelectedEmployee().getEmpJob().getJobTitle());
        //if the job details have been assigned already they are also displayed in the text boxes
    }//GEN-LAST:event_cboEmpNoActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        /**
         *The Button creates a job using the values entered by the user
         *Calls the setJobObject method defined in the Employee class passing to it the Job Object.
         */
        if ((!txtJDept.getText().isEmpty())&&(!txtJTitle.getText().isEmpty())) {
            Job jobObj = new Job(txtJTitle.getText(), txtJDept.getText());
            //*the locally declared getSelected employee method is used
            getSelectedEmployee().setEmpJob(jobObj);
            clearControls();
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter both The Job Title & Job Department");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cboEmpNo;
    private javax.swing.JLabel lblCboEmpNo;
    private javax.swing.JLabel lblDept;
    private javax.swing.JLabel lblEmpName;
    private javax.swing.JLabel lblEmpNo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnEmploEntry;
    private javax.swing.JTextField txtEmpName;
    private javax.swing.JTextField txtEmpNo;
    private javax.swing.JTextField txtJDept;
    private javax.swing.JTextField txtJTitle;
    // End of variables declaration//GEN-END:variables
}
